### ISSUE TITLE
Potential licensing problems

### ISSUE THREAD

**Issue by white-axe** [Speak2Erase/alox-48#4]
Why is this library licensed under GPL? The GPL prevents applications that are not licensed under GPL or AGPL from linking with GPL-licensed libraries (https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL). Usually, libraries using a copyleft license are licensed under the LGPL instead.

**Comment by melody-rs** [comment]
Will relicense under LGPL when I get a chance (probably after merging drop-serde).
